/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'psempl001c' at '5/22/18 6:00 PM' with Gradle 2.14.1
 *
 * @author psempl001c, @date 5/22/18 6:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
